---
name: practical-08
break: true
indent: 4
---
writing:
    reflection.md:
        ConfirmFileExists
        CountFileWords --count 450
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountMarkdownTags --tag "heading" --count 3
        CountFileParagraphs --count 3